### ISSUE TITLE
关于数据源配置

### ISSUE THREAD

**Issue by Lovnx** [johntostring/spring-boot-shiro#7]
我在工程中已经有了一套datasource，我再配置：

```
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: 
    password: 
    driver-class-name: com.mysql.jdbc.Driver
```

就会报错了：
```
Description:

Parameter 0 of method getAuthorizationAttributeSourceAdvisor in com.millinch.spring.boot.autoconfigure.shiro.ShiroConfiguration required a bean named 'dataSource' that could not be found.


Action:

Consider defining a bean named 'dataSource' in your configuration.
```
